version: "3.8"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: sh -c "npm install && npm run dev"
        container_name: app
        volumes:
            - ./src:/src/
        networks:
            - appnet
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'db'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - appnet
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        networks:
            - appnet
        depends_on:
            - app

networks:
    appnet:
        driver: bridge